### ISSUE TITLE
kyd-qt: Does not work on ARCH-Linux systems 

### ISSUE THREAD

**Issue by h6y34ui98** [kydcoin/KYD3#2]
./kyd-qt: error while loading shared libraries: 
       `` libboost_chrono.so.1.58.0 => not found
	libqrencode.so.3 => not found
	libprotobuf.so.9 => not found
	libdb_cxx-4.8.so => not found
	libminiupnpc.so.10 => not found
	libevent_pthreads-2.0.so.5 => not found
	libevent-2.0.so.5 => not found``

**Comment by PaulH-RESQ** [comment]
New version is now compatible with Arch Linux
